"""
Prometheus metrics for the trading bot.
All key counters, gauges, and histograms from the spec.
"""
from prometheus_client import Counter, Gauge, Histogram

# ── Trade metrics ───────────────────────────────────────────────────────
trades_total = Counter(
    "trades_total",
    "Total trades executed",
    ["exchange", "symbol", "side", "mode"],
)
signals_generated = Counter(
    "signals_generated_total",
    "Total signals generated by agents",
    ["agent"],  # watcher, analyzer, context
)
decisions_made = Counter(
    "decisions_made_total",
    "Total decisions made by Bayesian engine",
    ["outcome"],  # enter, skip, reject
)

# ── Position metrics ────────────────────────────────────────────────────
active_positions = Gauge(
    "active_positions",
    "Number of currently open positions",
)
portfolio_value = Gauge(
    "portfolio_value_usd",
    "Current portfolio value in USD",
)
account_equity = Gauge(
    "account_equity_usd",
    "Current account equity in USD",
)

# ── Performance metrics ─────────────────────────────────────────────────
win_rate = Gauge(
    "win_rate",
    "Rolling win rate (0-1)",
)
avg_r_multiple = Gauge(
    "avg_r_multiple",
    "Average R-multiple of closed trades",
)
current_drawdown = Gauge(
    "current_drawdown_pct",
    "Current drawdown percentage from peak",
)

# ── Timing metrics ──────────────────────────────────────────────────────
cycle_duration = Histogram(
    "cycle_duration_seconds",
    "Time taken for each trading cycle",
    buckets=[30, 60, 90, 120, 180, 300, 600],
)
api_latency = Histogram(
    "api_latency_seconds",
    "API call latency",
    ["exchange", "endpoint"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0],
)

# ── Error metrics ───────────────────────────────────────────────────────
errors_total = Counter(
    "errors_total",
    "Total errors encountered",
    ["component", "error_type"],
)
